
- hosts: all
  become: yes
  tasks:
    - name: Download node_exporter tarball
      command: wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz

    - name: Extract node_exporter tarball
      command: tar -xf node_exporter-1.5.0.linux-amd64.tar.gz

    - name: Move node_exporter binary to /usr/local/bin
      command: mv node_exporter-1.5.0.linux-amd64/node_exporter  /usr/local/bin

    - name: Cleanup extracted files
      command: rm -rv node_exporter-1.5.0.linux-amd64*

    - name: Create node_exporter user
      command: useradd -rs /bin/false node_exporter

    - name: Create systemd service file using heredoc and tee
      shell: |
        cat <<EOF | tee /etc/systemd/system/node_exporter.service
        [Unit]
        Description=Node Exporter
        After=network.target

        [Service]
        User=node_exporter
        Group=node_exporter
        Type=simple
        ExecStart=/usr/local/bin/node_exporter

        [Install]
        WantedBy=multi-user.target
        EOF
      become: yes


    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable node_exporter service
      command: systemctl enable node_exporter

    - name: Start node_exporter service
      command: systemctl start node_exporter.service

    - name: Check node_exporter status
      command: systemctl status node_exporter.service --no-pager
      register: status
      ignore_errors: yes

    - name: Show node_exporter status output
      debug:
        var: status.stdout_lines
      
      
      
   
      
      

      
       
        
        
