- hosts: all
  become: yes
  vars:
    tomcat_version: "10.1.55"
  tasks:
    - name: install java
      command: sudo apt install openjdk-17-jdk wget -y

    - name: download tomcat from dlcdn
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/root/"

    - name: untar the apache file
      command: tar -zxvf apache-tomcat-{{ tomcat_version }}.tar.gz


    - name: rename the tomcat
      command: mv apache-tomcat-{{ tomcat_version }} tomcat
      tags: abc

    - name: Insert Tomcat manager roles and user before </tomcat-users>
      command: >
        sed -i '/<\/tomcat-users>/ i\ <role rolename="manager-gui"/>\n<role rolename="manager-script"/>\n<user username="tomcat" password="raham123" roles="manager-gui, manager-script"/>' /root/tomcat/conf/tomcat-users.xml

    - name: Remove restrictive Valve entry from context.xml
      command: >
        sed -i '/<Valve className="org.apache.catalina.valves.RemoteCIDRValve"/,/\/>$/d' /root/tomcat/webapps/manager/META-INF/context.xml

    - name: start the tomcat
      shell: sh /root/tomcat/bin/startup.sh
